### ISSUE TITLE
The themes that must be toggled via the title-bar are not Adwaita.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [flathub/com.belmoussaoui.Decoder#5]
This is meaning that its visual appearance is not consistent with any other software.

**Comment by roke-julian-lockhart** [comment]
http://gitlab.gnome.org/World/decoder/-/issues/27 may be relevant.

**Comment by A6GibKm** [comment]
I am going to close this, as it is a problem related to the app and not the flatpak distribution of the app. Just note that the dark switch in the app just uses the gtk setting for dark mode.

**Comment by roke-julian-lockhart** [comment]
> http://github.com/flathub/com.belmoussaoui.Decoder/issues/5#issuecomment-920356788

http://gitlab.gnome.org/World/decoder/-/issues/27
